[package]
name = "lfdb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.8.2"
thiserror = "1.0.51"
crc32fast = "1.5.0"
libc = "0.2.182"
winapi = "0.3.9"
crossbeam-skiplist = "0.1.3"
log = { version = "0.4.29" }
uuid = { version = "1.23.2", features = ["v4"] }
hashbrown = { version = "0.17.1" }


[dev-dependencies]
tempfile = "3.10.1"
rand = "0.9.4"


[workspace]
members = ["bench"]

[lints]
clippy.unit_arg = "allow"
clippy.doc_lazy_continuation = "allow"
clippy.doc_overindented_list_items = "allow"
clippy.module_inception = "allow"
clippy.too_many_arguments = "allow"
clippy.type_complexity = "allow"
clippy.upper_case_acronyms = "allow"
clippy.manual_is_multiple_of = "allow"
clippy.big_endian_bytes = "deny"
