[alias]
"test:cov:html" = "llvm-cov --package lfdb --html --open --tests"
"test:cov" = "llvm-cov --package lfdb --fail-under-functions 80 --fail-under-lines 80 --fail-under-regions 80 --tests -- --test-threads 1"
"benchmark" = "bench --package bench"
