name: CI

on:
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Free disk space
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /usr/local/share/boost "$AGENT_TOOLSDIRECTORY"
          sudo apt-get clean

      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: Install coverage tool
        run: command -v cargo-llvm-cov || cargo install cargo-llvm-cov

      - name: Check format
        run: cargo fmt --all -- --check
      - name: Check lint
        run: cargo clippy --all-targets -- -D warnings
      - name: Run tests
        run: cargo test:cov

  benchmark_ycsb:
    runs-on: ubuntu-latest
    steps:
      - name: Free disk space
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /usr/local/share/boost "$AGENT_TOOLSDIRECTORY"
          sudo apt-get clean

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Switch to main baseline
        run: git switch --detach ${{ github.event.pull_request.base.sha }}

      - name: YCSB baseline
        run: cargo benchmark --bench ycsb --features lfdb -- --save-baseline main --quiet
        continue-on-error: true

      - name: Switch to PR branch
        run: git switch --detach ${{ github.event.pull_request.head.sha }}

      - name: YCSB (PR vs main)
        run: cargo benchmark --bench ycsb --features lfdb -- --baseline-lenient main
